package com.airline.iotdemo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Food implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Type")
	@org.kie.api.definition.type.Description("Type of food.")
	private java.lang.String type;

	@org.kie.api.definition.type.Label("Max Temperature")
	@org.kie.api.definition.type.Description("Food is considered spoiled at higher temperatures.")
	private java.lang.Double maxTemperature;

	@org.kie.api.definition.type.Label("Min Temperature")
	@org.kie.api.definition.type.Description("Food is considered frozen at lower temperatures.")
	private java.lang.Double minTemperature;

	@org.kie.api.definition.type.Description("Name of the food.")
	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;

	@org.kie.api.definition.type.Description(value = "Food RFID")
	@org.kie.api.definition.type.Label(value = "RFID")
	private java.lang.String rfid;

	public Food() {
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.Double getMaxTemperature() {
		return this.maxTemperature;
	}

	public void setMaxTemperature(java.lang.Double maxTemperature) {
		this.maxTemperature = maxTemperature;
	}

	public java.lang.Double getMinTemperature() {
		return this.minTemperature;
	}

	public void setMinTemperature(java.lang.Double minTemperature) {
		this.minTemperature = minTemperature;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getRfid() {
		return this.rfid;
	}

	public void setRfid(java.lang.String rfid) {
		this.rfid = rfid;
	}

	public Food(java.lang.String type, java.lang.Double maxTemperature,
			java.lang.Double minTemperature, java.lang.String name,
			java.lang.String rfid) {
		this.type = type;
		this.maxTemperature = maxTemperature;
		this.minTemperature = minTemperature;
		this.name = name;
		this.rfid = rfid;
	}

}