package com.airline.iotdemo;

import org.kie.api.definition.type.Label;
import org.kie.api.definition.type.Description;

/**
 * This class was automatically generated by the data modeler tool.
 */

@Label("FOODCONTAINER")
@Description("Food Container")
public class Food implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@Label("RFIDTYPE")
	@Description("Type of food.")
	private String type;

	@Description("Food RFID")
	@Label("RFID")
	private String rfid;

	public Food() {
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getRfid() {
		return this.rfid;
	}

	public void setRfid(String rfid) {
		this.rfid = rfid;
	}

	public Food(String type, String rfid) {
		this.type = type;
		this.rfid = rfid;
	}

}
