package com.airline.iotdemo;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Tray")
@org.kie.api.definition.type.Description("A food tray")
public class Tray implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Type")
	private java.lang.String type;
	@org.kie.api.definition.type.Label("Prepared Date")
	@org.kie.api.definition.type.Description("Date of preparation of the food.")
	private java.util.Date preparedDate;
	@org.kie.api.definition.type.Label("Spoilage Date")
	@org.kie.api.definition.type.Description("Date of spoilage of the food.")
	private java.util.Date spoilageDate;

	@org.kie.api.definition.type.Label("Foods")
	@org.kie.api.definition.type.Description("A collection of food items in the tray.")
	private java.util.List<com.airline.iotdemo.Food> foods;

	@org.kie.api.definition.type.Description("Tray ID")
	@org.kie.api.definition.type.Label("ID")
	private java.lang.String id;

	@org.kie.api.definition.type.Description(value = "Food status code.")
	@org.kie.api.definition.type.Label(value = "Food Status")
	private java.lang.Integer foodStatus;

	public Tray() {
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.util.Date getPreparedDate() {
		return this.preparedDate;
	}

	public void setPreparedDate(java.util.Date preparedDate) {
		this.preparedDate = preparedDate;
	}

	public java.util.Date getSpoilageDate() {
		return this.spoilageDate;
	}

	public void setSpoilageDate(java.util.Date spoilageDate) {
		this.spoilageDate = spoilageDate;
	}

	public java.util.List<com.airline.iotdemo.Food> getFoods() {
		return this.foods;
	}

	public void setFoods(java.util.List<com.airline.iotdemo.Food> foods) {
		this.foods = foods;
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.Integer getFoodStatus() {
		return this.foodStatus;
	}

	public void setFoodStatus(java.lang.Integer foodStatus) {
		this.foodStatus = foodStatus;
	}

	public Tray(java.lang.String type, java.util.Date preparedDate,
			java.util.Date spoilageDate,
			java.util.List<com.airline.iotdemo.Food> foods,
			java.lang.String id, java.lang.Integer foodStatus) {
		this.type = type;
		this.preparedDate = preparedDate;
		this.spoilageDate = spoilageDate;
		this.foods = foods;
		this.id = id;
		this.foodStatus = foodStatus;
	}

}